spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/blog_app
    username: root
    
  #JPA configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #mail configuration  
  mail:
    host: smtp.gmail.com
    password: nsatooddfcvugvtv
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: shribinwade.100@gmail.com
